// Trade/service category dictionary (Spanish + English)
module.exports = {
  'Painting': ['pintura','pintar','painter','painting','pintor','pintora'],
  'Plumbing': ['plomero','plomera','plomeria','plomería','plumber','plumbing','fontanero','fontanera'],
  'Electrical': ['electricista','electrician','electrical work'],
  'Roofing': ['roofing','roofer','roof repair','techo','techos','techero','techador'],
  'Drywall': ['drywall','sheetrock','tablarroca','tablaroca'],
  'Flooring & Tile': ['tile install','tiles install','pisos','flooring','floor install','laminate floor','vinyl floor','hardwood floor','azulejo','azulejos','piso laminado'],
  'Concrete & Masonry': ['concrete','concreto','cemento','cement work','albañil','albanil','albañilería','albanileria','mason','masonry','losa','losas','ladrillo','ladrillos','sidewalk','driveway','foundation','cimiento','cimientos','block wall','bloque','bloques','rebar','varilla'],
  'Remodeling': ['remodelacion','remodelación','remodel','remodeling','renovación','renovacion','renovation','renovar'],
  'General Construction': ['construccion','construcción','construction worker','build homes','contratista general','general contractor'],
  'Carpentry': ['carpintero','carpintera','carpinteria','carpintería','carpenter','carpentry','trabajos de madera'],
  'Framing': ['framing','framer','framers'],
  'Siding & Stucco': ['siding','stucco','estuco'],
  'Demolition': ['demolition','demolicion','demolición','demoler','tumbar paredes'],
  'Insulation': ['insulation','aislamiento','aislante'],
  'Windows & Doors': ['window install','windows install','instalacion de ventanas','instalación de ventanas','door install','doors install'],
  'Cabinets & Countertops': ['cabinets','gabinetes','countertop','countertops','encimera','closets'],
  'Deck & Patio': ['deck install','decks','patio cover','pergola'],
  'Fencing': ['fencing','fence install','fences','cerca ','cercas','malla ciclonica'],
  'HVAC': ['hvac','aire acondicionado','a/c repair','ac repair','air condition','calefaccion','calefacción','heating repair'],
  'Welding': ['welding','welder','soldador','soldadura','soldar'],
  'Pressure Washing': ['pressure wash','power wash','lavado a presion','lavado a presión'],
  'Landscaping & Lawn': ['jardinero','jardineria','jardinería','jardin','jardín','landscaping','lawn care','lawn service','lawn mowing','yard work','pasto','cortar pasto','corto grama','corto pasto','corte de grama'],
  'Tree Services': ['tree removal','tree trimming','tree service','arboles','árboles','cortar arboles','cortar árboles','poda de','derribo de arboles'],
  'Pool Service': ['pool service','pool repair','piscina','alberca','mantenimiento de piscina'],
  'Moving': ['mudanza','mudanzas','moving service','mover muebles','servicio de mudanza'],
  'Hauling & Junk Removal': ['hauling','junk removal','basura','escombro','escombros','scrap metal','recojo basura'],
  'Mechanic': ['mecanico','mecánico','mecanica','mechanic','mechanic shop','taller mecanico','taller mecánico','auto repair'],
  'Auto Body & Paint': ['body shop','hojalateria','hojalatería','pintura de carros','auto paint','collision repair','hojalatero'],
  'Towing': ['towing','grua service','grúa service','tow truck'],
  'Car Detailing': ['car detailing','detailing service','lavado de carros','car wash service'],
  'Tire Service': ['tire service','tire shop','llantera','used tires','llantas usadas'],
  'Barber & Hair': ['peluquero','peluquera','barber','barbero','barberia','barbería','haircut','cortes de cabello','cortes de pelo','estilista'],
  'Nails': ['nails salon','uñas acrilicas','uñas gel','manicure','pedicure','uñas ','acrilicas'],
  'Makeup': ['makeup artist','maquillaje profesional','maquillista','maquilladora'],
  'Photography': ['photography','fotografia','fotografía','fotografo','fotógrafo','fotografa','fotógrafa','photographer','sesion de fotos','sesión de fotos'],
  'Massage & Spa': ['masajes','massage therapist','masaje relajante','day spa','spa service'],
  'Catering & Home Food': ['catering','vendo comida','hago comida','vendo tamales','vendo pupusas','vendo tacos','hago pasteles','cater','venta de comida','comida a domicilio','vendo tortillas','hago tamales'],
  'Bakery & Pastries': ['panadero','panadera','panaderia','panadería','bakery','baker','pasteles','cakes','postres','pastry','reposteria','repostería'],
  'Restaurant': ['restaurant','restaurante','taqueria','taquería','pupuseria','pupusería','lonchera','food truck'],
  'Childcare': ['daycare','childcare','cuidado de niños','cuido ninos','cuido niños','niñera','ninera','babysitter','guarderia','guardería','after school care'],
  'Tutoring': ['tutor ','tutoring','clases de ingles','clases de inglés','clases de matematicas','clases de matemáticas','enseño','private classes'],
  'Translation': ['translation service','traduccion','traducción','traductor','traductora','interpreter','interprete','intérprete'],
  'Taxes & Notary': ['notario','notary','taxes','impuestos','tax prep','preparacion de taxes','preparación de taxes','preparador de taxes','itin'],
  'Insurance': ['seguros','insurance agent','agente de seguros','poliza de seguro','póliza de seguro'],
  'Real Estate': ['real estate','bienes raices','bienes raíces','realtor','agente inmobiliario','vendo casa','rento casa'],
  'Legal Services': ['abogado','abogada','lawyer','attorney','consulta legal','asesoria legal','asesoría legal'],
  'Accounting': ['contador','contadora','accountant','bookkeeping','contabilidad'],
  'Trucking & CDL': ['trailero','trucker','cdl driver','truck driver','camionero','owner operator'],
  'Delivery': ['delivery','entrega','reparto','reparto a domicilio','envios','envíos'],
  'Driver & Rides': ['viajes a','rides to','transporte a','chofer particular','uber driver'],
  'Cleaning': ['limpieza','limpiar casas','cleaning service','housekeeping','limpio casas','house cleaning','maid service','limpieza profunda'],
  'Handyman': ['handyman','todero','mantenimiento general','odd jobs','reparaciones en general'],
  'Sewing & Tailoring': ['costura','sewing','costurera','seamstress','tailor','sastre','arreglos de ropa'],
  'Warehouse Work': ['warehouse job','warehouse worker','bodega trabajo','almacen trabajo'],
  'Labor / Helper': ['helper','ayudante','ayudantes','laborer','jornalero','busco trabajadores','hiring workers'],
  'Events & Party': ['eventos','party rental','alquiler de mesas','decoracion de eventos','decoración de eventos','party planning','quinceañera','quinceanera','salon de eventos','salón de eventos'],
  'Music & DJ': ['dj para','música en vivo','musica en vivo','banda musical','mariachi','grupo musical','sonido profesional'],
  'Healthcare Worker': ['enfermera','nurse','caregiver','cuidador de ancianos','home care','asistente medico','asistente médico'],
  'Fitness & Training': ['personal trainer','entrenador personal','gym trainer','coach fitness'],
};
